name: Nightly Blog Review

on:
  schedule:
    - cron: '0 0 * * *'  # Every night at 00:00 UTC
  workflow_dispatch:

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run review agent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: yourusername/yourrepo
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/nightly_review.py
